### ISSUE TITLE
Frist nach Steiermärkischem Auskunftspflichtgesetz: 8, nicht 4 Wochen

### ISSUE THREAD

**Issue by hutershvili** [fin/fragdenstaat.at_old_2019#11]
Die Antwort-Frist für Behörden, die dem Steiermärkischen Auskunftspflichtgesetz unterliegen, scheint im System auf 4 Wochen eingestellt zu sein. Die Frist beträgt jedoch 8 Wochen (https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=LrStmk&Gesetzesnummer=20000804)

**Comment by fin** [comment]
thx, fixed
