### ISSUE TITLE
change link: Begründung für politische Entscheidung – MeineAbgeordneten

### ISSUE THREAD

**Issue by hutershvili** [fin/fragdenstaat.at_old_2019#14]
=> Neue Anfrage stellen => Behörde auswählen =>
unter: Welche Art von Information benötigen Sie?
=> Auswahl: Begründungen für politische Entscheidungen

=> "Klicken Sie hier, um zu meineabgeordneten.at zu gelangen."
Link derzeit: abgeordnetenwatch.de. Sollte auf https://www.meineabgeordneten.at/ geändert werden

**Comment by fin** [comment]
fixed \o/
