### ISSUE TITLE
Template disappears if you paste text and then want to edit it

### ISSUE THREAD

**Issue by hutershvili** [fin/fragdenstaat.at_old_2019#18]
If you want to submit a request => https://fragdenstaat.at/anfrage-stellen/ and paste or write something in the form, and then click to edit the whole letter ("vorlage bearbeiten"), the text provided by the template disappears. 

This does not appear to happen if you click "vorlage bearbeiten" while you haven't written or pasted anything into the form.

**Comment by fin** [comment]
That happens to enable switching back and forth between the modes - either you write everything, or you get the boilerplate. Would be hard to enable switching back otherwise. Working as intended, IMO.
