### ISSUE TITLE
Referenz zu Vorarlberger Auskunftsgesetz

### ISSUE THREAD

**Issue by hutershvili** [fin/fragdenstaat.at_old_2019#5]
Bei Anfragen an Institutionen verweist der vorgefertigte Text der Nachricht auf das falsche Gesetz: 
header: "hiermit beantrage ich gem DokWG die Erteilung folgender Auskunft:"
korrekt sollte es lauten: "hiermit beantrage ich gem Vorarlberger Auskunftsgesetz die Erteilung folgender Auskunft:

footer derzeit: "Mit freundlichen Grüßen 
Für den Fall der Verweigerung der Erteilung der beantragten Auskunft beantrage ich die Ausstellung eines Bescheides gem § 11 DokWg.  Sollten Kosten anfallen, bitte ich um vorherige Absprache.  Ich bitte weiters um Informationen bezüglich eventuellen Bedingungen zur Weiterverwendung der in der Antwort enthaltenen Daten."

sollte lauten: "Für den Fall der Verweigerung der Erteilung der beantragten Auskunft beantrage ich die Ausstellung eines Bescheides gem § 4 Auskunftsgesetz. Sollten Kosten anfallen, bitte ich um vorherige Absprache. Ich bitte weiters um Informationen bezüglich eventuellen Bedingungen zur Weiterverwendung der in der Antwort enthaltenen Daten.
Mit freundlichen Grüßen"

AuskunftsG: https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=LrVbg&Gesetzesnummer=20000078

**Comment by fin** [comment]
Fixed, sorry!
