### ISSUE TITLE
Tiroler Landesgesetz: Änderung der Referenz von TIWG auf Tiroler Auskunftspflichtgesetz

### ISSUE THREAD

**Issue by hutershvili** [fin/fragdenstaat.at_old_2019#7]
Bei Tiroler Landesbehörden lautet die Referenz derzeit:
"hiermit beantrage ich gem § 5 TIWG die Erteilung folgender Auskunft:"

diese Referenz sollte lauten: 
"hiermit beantrage ich gem § 2 Tiroler Auskunftspflichtgesetz die Erteilung folgender Auskunft:"

Der Footer des Templates lautet: 
"Mit freundlichen Grüßen 
Für den Fall der Verweigerung der Erteilung der beantragten Auskunft beantrage ich die Ausstellung eines Bescheides gem § 13 TIWG.  Sollten Kosten anfallen, bitte ich um vorherige Absprache.  Ich bitte weiters um Informationen bezüglich eventuellen Bedingungen zur Weiterverwendung der in der Antwort enthaltenen Daten."

er sollte lauten: 

"Für den Fall der Verweigerung der Erteilung der beantragten Auskunft beantrage ich die Ausstellung eines Bescheides gem § 4 Tiroler Auskunftspflichtgesetz. Sollten Kosten anfallen, bitte ich um vorherige Absprache. Ich bitte weiters um Informationen bezüglich eventuellen Bedingungen zur Weiterverwendung der in der Antwort enthaltenen Daten.

Mit freundlichen Grüßen"

**Comment by fin** [comment]
weird! fixed!

**Comment by fin** [comment]
das mit der grußformel muss ich getrennt davon einmal ansehen.
